name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src
    - name: Build Core Lib
      run: dotnet build ./src/TinyPubSub --no-restore
    - name: Test Core Lib
      run: dotnet test ./src/TinyPubSub.Tests  --verbosity normal
