name: CI

on:
  create:
    branches:
      - release/**
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    env:
      BUILD_CONFIG: "Release"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Build Version
        run: |
          Import-Module .\build\GetBuildVersion.psm1
          Write-Host $Env:GITHUB_REF
          $version = GetBuildVersion -VersionString $Env:GITHUB_REF
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: nuget restore ./src

      - name: Build
        run: dotnet build ./src/TinyPubSub --no-restore --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore

      - name: Run tests
        run: dotnet test ./src/TinyPubSub.Tests /p:Configuration=$BUILD_CONFIG /p:Version=$BUILD_VERSION --verbosity normal

      - name: Publish
        if: startsWith(github.ref, 'refs/heads/release')
        run: nuget push ./src/TinyPubSub/**/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
